[package]
name = "system_metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.20"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"